/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3/samples
 */

plugins {
    idea
    kotlin("jvm") version "1.8.0"

    // https://github.com/ryandens/javaagent-gradle-plugin
    id("com.ryandens.javaagent-application") version "0.4.2"
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
    }

    configure<JavaPluginExtension> {
        sourceCompatibility = JavaVersion.VERSION_15
        targetCompatibility = JavaVersion.VERSION_15
    }
}

dependencies {
    implementation("org.aspectj:aspectjweaver:1.9.21.1")
    javaagent("org.aspectj:aspectjweaver:1.9.21.1")
}

tasks {
    withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        kotlinOptions {
            jvmTarget = "15"
        }
    }
}
